---
- include_tasks: manual_link.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= '14'

- include_tasks: dependencies.yml
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= '14')

- name: Looking for Data disk
  stat: path="{{ item.disk }}"
  register: ret_stat_disk
  with_items:
   - "{{ disk_devices }}"

- debug: msg="{{ret_stat_disk}}"
- debug: msg="{{disk_devices}}"

- name: Starting partition configuration
  include_tasks: partition.yml
  when: ret_stat_disk is defined
  with_items:
    - "{{ ret_stat_disk.results }}"
  loop_control:
    loop_var: item_disk_devices

- name: Setup LVOL
  include_tasks: lvm.yml
  when:
    - disk_lvol is defined
    - not ansible_check_mode
  with_items:
    - "{{ disk_lvol }}"
  loop_control:
    loop_var: item_disk_lvol
  register: ret_setup_lvm

- import_tasks: fs.yml
- import_tasks: mount.yml
