#!/bin/bash

PATH="${PATH}:/usr/sbin"

for blkdev in $( nvme list | awk '/^\/dev/ { print $1 }' ) ; do
  mapping="/dev/$(nvme id-ctrl --raw-binary "${blkdev}" 2> /dev/null| cut -c3073-3104 | tr -s ' ' | sed 's/ $//g')"
  if [[ "$mapping" == "/dev/" ]]; then
	  continue
  fi
  dev_prefix="/dev"
  mapping=${mapping/#$dev_prefix} #remove /dev/ prefix if present
  ( test -b "${blkdev}" && test -L "${mapping}" ) || ln -fs "${blkdev}" "${mapping}"
done
